### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by mnosov622** [mnosov622/todo-list#12]
Add switch, so that user will be able to switch between dark and light more.

Something like that 
![image](https://user-images.githubusercontent.com/73063742/195752270-491c5081-7426-41b7-b72f-9a665c278bfa.png)

**Comment by UditNS** [comment]
Hi @mnosov622, I would like to do this task.

**Comment by UditNS** [comment]
<img width="1440" alt="Screenshot 2022-10-14 at 10 21 59 AM" src="https://user-images.githubusercontent.com/102902271/195765140-e18a446c-60b1-4a7f-812e-593e5ca52054.png">


Do you want any changes ??

**Comment by mnosov622** [comment]
Looks great !

I think it's better to change the text color and design as well.

Thank you.

**Comment by UditNS** [comment]
Wait a minute I am doing it

**Comment by UditNS** [comment]
<img width="1440" alt="Screenshot 2022-10-14 at 10 41 10 AM" src="https://user-images.githubusercontent.com/102902271/195767178-f2b8c46e-86d1-405d-8683-aeabe0532684.png">


Now any changes

**Comment by mnosov622** [comment]
That looks very good, can you make a PR, so I can take a look locally.

**Comment by UditNS** [comment]
Done, you can check it locally
