### ISSUE TITLE
Allow marking multiple tasks as completed by holding SHIFT

### ISSUE THREAD

**Issue by mnosov622** [mnosov622/todo-list#14]
While holding shift, clicking on 1st task and last should mark as completed all tasks between them.

**Comment by jatin00000** [comment]
Hi @mnosov622, can I work on this issue.

**Comment by mnosov622** [comment]
Sure!

**Comment by jatin00000** [comment]
Hi @mnosov622, I had solved the issue and made the pull request. https://github.com/mnosov622/todo-list/pull/30
Please review and merge it.
Thank You
