### ISSUE TITLE
Make nav bar look better

### ISSUE THREAD

**Issue by mnosov622** [mnosov622/todo-list#16]

**Comment by yogesh-9999** [comment]
assign it to me

**Comment by mnosov622** [comment]
Please work on another issue. Sorry, but you can't have 2 issues at the same time.

**Comment by jatin00000** [comment]
Please assign me this issue.

**Comment by DarkSoul26** [comment]
@mnosov622 can you assign this issue to me?

**Comment by mnosov622** [comment]
Sure !

**Comment by DarkSoul26** [comment]
#20 the navbar is successfully changed. 
@mnosov622 take a look into it.
