### ISSUE TITLE
After page refresh, unable to mark task as completed

### ISSUE THREAD

**Issue by mnosov622** [mnosov622/todo-list#5]
Steps to reproduce:

1. Add a couple of tasks

2. Refresh the page

Actual Result:

Clicking on task doesn't mark it as completed

Expected Result

Clicking on task marks it as completed by crossing out the word and adding icon.

**Comment by alexsam29** [comment]
Hi, I can try to solve this issue.

**Comment by mnosov622** [comment]
Hi!

Sure, go ahead :)
