### ISSUE TITLE
Enhancing the Light/Dark Mode feature.

### ISSUE THREAD

**Issue by theravi04** [mnosov622/todo-list#50]
Adding a light and dark mode toggle button to apply mode changes to each part of website including the navbar, Enhancing the feature.
@mnosov622 kindly assign me this under Hacktoberfest2022.

**Comment by mnosov622** [comment]
Sure !

**Comment by ravi4488** [comment]
@mnosov622 kindly review my PR #53 .

**Comment by theravi04** [comment]
@mnosov622 kindly review my PR #53
