### ISSUE TITLE
background image creates distraction on webpage from its main content

### ISSUE THREAD

**Issue by ShailavMalik** [mnosov622/todo-list#60]
background image creates a sort of distraction on the webpage and that written part mainly.
Suggestions:

1.  It can be replaced with a beautiful color gradient or 
2. a background image by which main focus stays on the contents of the webpage or
3.  reduce the opacity of the image .

**Comment by ShailavMalik** [comment]
@mnosov622 please check if anything can be done to make the UI cleaner.

**Comment by PakaVishwaTeja** [comment]
assign this to me! I have some ideas:)
