### ISSUE TITLE
Fix the logo link to website

### ISSUE THREAD

**Issue by mnosov622** [mnosov622/todo-list#9]
The logo link should go to the index page, but now it's wrong.

**Comment by DPRIYATHAM** [comment]
Hello, 
I am interested to work on this, can you specify which link it has to be directed to?

**Comment by mnosov622** [comment]
Hi !

It should go to /todo-list

**Comment by DPRIYATHAM** [comment]
Ok
thank you, I will work on it.

**Comment by jatin00000** [comment]
I had fixed the bug. https://github.com/mnosov622/todo-list/pull/18
Please review and merge my pull request.
Thank You
